import './globals.css'
import { Karla } from 'next/font/google'

const karla = Karla({ 
  subsets: ['latin'],
  variable: '--font-karla'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={karla.variable} >
        <main className='flex font-sans bg-stone-50 h-full items-center gap-5 flex-col'>
        {children}
        </main>
      </body>
    </html>
  )
}
